[package]
name = "zatsu"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.17", features = ["derive"] }
flate2 = "1.0.30"
hex-string = "0.1.0"
serde = "1.0.200"
serde_derive = "1.0.200"
serde_json = "1.0.116"
sha1 = "0.10.6"
sha2 = "0.10.8"
